export ZSH="/root/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git autojump colored-man-pages command-not-found zsh-autosuggestions zsh-syntax-highlighting)

source "$ZSH/oh-my-zsh.sh"

# Ubuntu's autojump package owns this integration file.
[[ -s /usr/share/autojump/autojump.zsh ]] && source /usr/share/autojump/autojump.zsh

export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
export LANGUAGE=zh_CN:zh
export TERM=xterm-256color
case ":${LS_COLORS:-}:" in
  *:ow=01\;34:tw=01\;34:*) ;;
  *) export LS_COLORS="${LS_COLORS:+${LS_COLORS}:}ow=01;34:tw=01;34" ;;
esac
